' Power From a Reservoir
#'
#' This function compute power generated by a flow rate from a reservoir at a given
#' height
#' @param height (m)
#' @param flow (m3/s)
#' @param rho density of water (default 1000 g/m3)
#' @param Keff reservoir efficiency
#' @param g acceleration due to gravity (m/s) default=9.8
#' @return power (W)
#' @author Naomi Tague

power_gen = function(height, flow, rho=1000, g=9.8, Keff=0.8) {
  
  # make sure we have same number of flow and height's so we can match them
  if (length(height) != length(flow)) return(" number of heights is different from number of flows")
  
  # make sure inputs are positive and if not set as NA so result will be NA
  height = ifelse( (height < 0), NA, height)
  
  # an alterative is to exit the function prematurely 
  flow = ifelse((flow < 0), return("flow must be greater than zero"), flow)
  
  #    return("Height cannot be less than 0")
  
  # calculate power
  result = rho * height * flow * g * Keff
  return(result)
}